#!/usr/bin/env bash

set -e
set -u
set -o pipefail

declare -a exclude_dirs
exclude_dirs=(
   "build"
   "dist"
   "assets"
)

exclude_dir_string() {
    local s=""
    for dir in "${exclude_dirs[@]}"; do
        s+="/$dir/|"
    done
    echo "${s::-1}"
}

find . -type f -iname \*.\*js | egrep -v "$(exclude_dir_string)"
