#!/usr/bin/env bash

set -e
set -u
set -o pipefail

declare -a exclude_dirs
exclude_dirs=(
   "build"
   "dist"
   "test"
   "asset"
)

make_exlude_dir_string() {
    local s=""
    for dir in "${exclude_dirs[@]}"; do
        s+=".*/$dir/|"
    done
    echo "${s::-1}"
}

exclude_dir_string="$(make_exlude_dir_string)"

find . -type f -iname \*.*js | egrep "($exclude_dir_string)"
